---
- name: Automação On-Premise - Patch de Segurança VMware
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Criar diretório de configuração para o time de segurança
      file:
        path: /etc/cloud-autoupdate
        state: directory
        mode: '0755'

    - name: Garantir arquivo de configuração padrão
      copy:
        dest: /etc/cloud-autoupdate/cloud-autoupdate.conf
        content: |
          [blacklist]
          blacklist = ""
        force: no

    - name: Rodar Script de Coleta (Get Packages)
      script: get_packages.py
      register: check_info

    - name: Mostrar pacotes vulneráveis no console do AWX
      debug:
        var: check_info.stdout_lines

    - name: Rodar Script de Atualização (Kernel e Seguranca)
      script: cloud_autoupdate.py
      register: update_result

    - name: Verificar se o sistema solicita reinicialização
      stat:
        path: /var/run/reboot-required
      register: reboot_pode_ser_necessario

    - name: Confirmar se o motivo é atualização de Kernel
      shell: "grep -E 'linux-image|linux-generic' /var/run/reboot-required.pkgs"
      register: kernel_check
      ignore_errors: true
      when: reboot_pode_ser_necessario.stat.exists
      changed_when: false

    - name: Reiniciar Servidor VMware (Somente se necessário)
      reboot:
        reboot_timeout: 600
        msg: "Reiniciando para aplicar novo Kernel via AWX"
      when: 
        - reboot_pode_ser_necessario.stat.exists
        - kernel_check.rc is defined and kernel_check.rc == 0
