---
- name: Automação On-Premise - Patch de Segurança VMware
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Criar diretório de configuração para o time de segurança
      file:
        path: /etc/cloud-autoupdate
        state: directory
        mode: '0755'

    - name: Garantir arquivo de configuração padrão
      copy:
        dest: /etc/cloud-autoupdate/cloud-autoupdate.conf
        content: |
          [blacklist]
          blacklist = ""
        force: no

    - name: Rodar Script de Coleta (Get Packages)
      script: get_packages.py
      register: check_info

    - name: Rodar Script de Atualização (Kernel e Seguranca)
      script: cloud_autoupdate.py
      register: update_result

    - name: Verificar se o Kernel ou pacotes críticos exigem reboot
      stat:
        path: /var/run/reboot-required
      register: reboot_status

    # Adicionei este debug para você ver o erro no console do AWX
    - name: Debug - Validar se o arquivo foi detectado
      debug:
        msg: "Status do arquivo de reboot: {{ reboot_status.stat.exists }}"

    - name: Reiniciar Servidor VMware (Apenas se o Kernel foi atualizado)
      reboot:
        reboot_timeout: 600
        msg: "Reiniciando via AWX para aplicar novo Kernel"
      when: reboot_status.stat.exists == true